name: printmax_app

description: "PrintMax Android app built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/login/

flutter_launcher_icons:
  image_path: assets/icon/icon.png
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/icon.png
